// auth
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const GET_DATA_USERS = "GET_DATA_USERS";
export const LOGOUT = "LOGOUT";
export const CHECK_NETWORK = "CHECK_NETWORK";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const REQUEST_RESET_PW = "REQUEST_RESET_PW";
export const MAYBE_LATER = "MAYBE_LATER";

// course
export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAILURE = "GET_COURSE_FAILURE";
export const GET_PLAYER_COURSE = "GET_PLAYER_COURSE";
export const GET_EXERCISE_SUCCESS = "GET_EXERCISE_SUCCESS";
export const GET_FILE_BONNUS_SUCCESS = "GET_FILE_BONNUS_SUCCESS";
export const MODAL_FIRST = "MODAL_FIRST";
export const GET_ID_COURSE_DETAIL = "GET_ID_COURSE_DETAIL";
export const GET_PROGRESS = "GET_PROGRESS";
export const NOT_GET_PLAYER_COURSE = "NOT_GET_PLAYER_COURSE";
export const BUY_A_COURSE = "BUY_A_COURSE";

// file attachment
export const GET_ATTACHMENT_SUCCESS = "GET_ATTACHMENT_SUCCESS";
export const PLAYER_READ_FILE = "PLAYER_READ_FILE";
export const PUSH_ATTM_PROGRESS = "PUSH_ATTM_PROGRESS";



// lesson
export const GET_LESSON_REQUEST = "GET_LESSON_REQUEST";
export const GET_LESSON_SUCCESS = "GET_LESSON_SUCCESS";


// player
export const ADD_PLAYER_REQUEST = "ADD_PLAYER_REQUEST";
export const ADD_PLAYER_SUCCESS = "ADD_PLAYER_SUCCESS";
export const ADD_PLAYER_FAILURE = "ADD_PLAYER_FAILURE";
export const GET_ID_IMAGE = "GET_ID_IMAGE";
export const GET_LIST_PLAYER_SUCCESS = "GET_LIST_PLAYER_SUCCESS";
export const ADD_PLAYER = "ADD_PLAYER";
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_PLAYER = "GET_PLAYER";
export const DELETE_PLAYER = "DELETE_PLAYER";
export const GET_HOMEWORK = "GET_HOMEWORK";
export const GET_CHECK_FILE = "GET_CHECK_FILE";
export const AVATAR_OFFLINE = "AVATAR_OFFLINE";
export const GET_COMMENTS = "GET_COMMENTS";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_WITH_IMAGE_SUCCESS = "POST_COMMENT_WITH_IMAGE_SUCCESS";

// profile

//MP3

export const ADD_DATA_MP3 = "ADD_DATA_MP3";
export const GET_MEDIA_MP3 = "GET_MEDIA_MP3";
export const GET_PAUSED_MP3 = "GET_PAUSED_MP3";
export const GET_CLOSE_PROGRESS_MP3 = "GET_CLOSE_PROGRESS_MP3";
export const GET_MUTED_MP3 = "GET_MUTED_MP3";
export const GET_TIMEVIDEO_MP3 = "GET_TIMEVIDEO_MP3";
export const GET_CHECK_MP3 = "GET_CHECK_MP3";
export const OPEN_MP3 = "OPEN_MP3";
export const CLEAR_MP3 = "CLEAR_MP3";
export const LIST_MUTED_REPEAT_MP3 = "LIST_MUTED_REPEAT_MP3";
export const SET_PROGRESS_MP3 = "SET_PROGRESS_MP3";
export const SET_ERR_MP3 = "SET_ERR_MP3";
// export const GET_ = "GET_";

// id_player
export const ID_PLAYER = "ID_PLAYER";

// async storage
export const GET_STORAGE_PLAYER = "GET_STORAGE_PLAYER";

